### PR TITLE
upgrade to Ubuntu 22.04

### PR DESCRIPTION
**Pull request by aerickson**
- upgrade system to python3 to 3.9 (3.10.4 is available, but breaks raptor) (was 3.6.9?)
- run_gw.py
  - use python3
  - changes for python3 compatibility
- unpin mozdevice
  - don't install mozfile
- remove pip commands
  - pip is the same as pip3 on 22.04 
- compared robustcheckout versions, but not upgrading
  - not many differences
- add InSpec testing of image

---

```bash
$ python3 --version
Python 3.9.13
```

### CODE REVIEW

**Comment by aerickson** [comment]
local testing looks good

**Comment by aerickson** [comment]
building f251a83 as 20220804T124127

**Comment by aerickson** [comment]
image has been built

```
08-08 21:56:49.988 20220804T124127: digest: sha256:31fd1210f891ac3b635bd6af339b69201dc2c00fa9fa56a2e92aa6201376b808 size: 5346
```

**Comment by aerickson** [comment]
try push #2 (first failed due to Bitbar cluster docker version, now upgraded): https://treeherder.mozilla.org/jobs?repo=try&revision=d36dc147fdb1abe4c95c1b21a76eaaa3a30bd1fb
- results are confusing (jobs are failing because they're running on a g5 and we have the wrong binary arch), but the docker image appears to be working fine.

**Comment by aerickson** [comment]
building 2e1caec as 20220902T133609

build successful.

`09-02 11:05:34.370 20220902T133609: digest: sha256:c70de87895c108e61fade6c23d59f6f152c25d3255543a19552fc50c8926e11b size: 5766`

testing in https://treeherder.mozilla.org/#/jobs?repo=try&revision=58ff4cbf683512d97d729ad8304f726a10f11fb8

results: BAD
- pips were installed under 3.10's path vs 3.9

**Comment by aerickson** [comment]
building 33613b3 as `20220902T165809`

built successfully `09-02 14:14:23.336 20220902T165809: digest: sha256:e9c36070b019a60cacbedf91eb6d4977820f591380561dc61c64199fde6df3f7 size: 5558`

testing with `./mach try fuzzy --full --artifact --query "'android-hw \!condprof \!live 'cnn 'geckoview"  --no-push` in https://treeherder.mozilla.org/#/jobs?repo=try&revision=e66aafc019a3f1d4bab387afd70a62bb3afc6b81
- results: looks good, running more tests

**Comment by aerickson** [comment]
second round of testing: `./mach try fuzzy --full --artifact --query "'test-android-hw 'geckoview \!'g5 'google | 'cnn" --no-push`
- https://treeherder.mozilla.org/jobs?repo=try&group_state=expanded&tier=1%2C2%2C3&revision=fbb81439bafa39e38b37affb2c73a0c761b501db
  - results: look good

**Comment by aerickson** [comment]
Made live in https://github.com/mozilla-platform-ops/mozilla-bitbar-devicepool/pull/31.

Everything looks good.

**Review by davehouse — APPROVED** [review]

**Pull request merged**
