### PR TITLE
upgrade mercurial

### PR DESCRIPTION
**Pull request by aerickson**
see https://bugzilla.mozilla.org/show_bug.cgi?id=1760840

local testing verifies version is upgraded with Dockerfile changes:
```
root@b8ed6141da22:~# hg --version
Mercurial Distributed SCM (version 6.1)
(see https://mercurial-scm.org for more information)

Copyright (C) 2005-2022 Olivia Mackall and others
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
root@b8ed6141da22:~#
```

### CODE REVIEW

**Comment by aerickson** [comment]
building as `20220322T145503`

build successful: `03-22 13:19:43.643 20220322T145503: digest: sha256:60d11f13323ca878d858fdd826c7a3e359456fb8f98181976c17bc3c28cbc11b size: 5967
`

test result: failure
```
[vcs 2022-03-30T21:07:17.325Z] adding file changes
[vcs 2022-03-30T21:07:19.517Z] added 4 changesets with 5 changes to 4 files (+1 heads)
[vcs 2022-03-30T21:07:19.518Z] new changesets 66b5f8936fa8:59ec5e25b59b (4 drafts)
[vcs 2022-03-30T21:07:19.779Z] (setting sparse config to profile build/sparse-profiles/perftest)
[vcs 2022-03-30T21:07:20.111Z] ** Unknown exception encountered with possibly-broken third-party extension "robustcheckout" (version N/A)
[vcs 2022-03-30T21:07:20.111Z] ** which supports versions 5.9 of Mercurial.
[vcs 2022-03-30T21:07:20.111Z] ** Please disable "robustcheckout" and try your action again.
[vcs 2022-03-30T21:07:20.111Z] ** If that fixes the bug please report it to the extension author.
[vcs 2022-03-30T21:07:20.111Z] ** Python 3.6.9 (default, Dec  8 2021, 21:08:43) [GCC 8.4.0]
[vcs 2022-03-30T21:07:20.111Z] ** Mercurial Distributed SCM (version 6.1)
[vcs 2022-03-30T21:07:20.111Z] ** Extensions loaded: histedit, purge, rebase, robustcheckout, share, sparse
[vcs 2022-03-30T21:07:20.111Z] Traceback (most recent call last):
[vcs 2022-03-30T21:07:20.111Z]   File "/usr/local/bin/hg", line 61, in <module>
[vcs 2022-03-30T21:07:20.143Z]     dispatch.run()
[vcs 2022-03-30T21:07:20.143Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 144, in run
[vcs 2022-03-30T21:07:20.143Z]     status = dispatch(req)
[vcs 2022-03-30T21:07:20.143Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 250, in dispatch
[vcs 2022-03-30T21:07:20.143Z]     status = _rundispatch(req)
[vcs 2022-03-30T21:07:20.143Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 294, in _rundispatch
[vcs 2022-03-30T21:07:20.143Z]     ret = _runcatch(req) or 0
[vcs 2022-03-30T21:07:20.143Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 470, in _runcatch
[vcs 2022-03-30T21:07:20.143Z]     return _callcatch(ui, _runcatchfunc)
[vcs 2022-03-30T21:07:20.143Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 480, in _callcatch
[vcs 2022-03-30T21:07:20.144Z]     return scmutil.callcatch(ui, func)
[vcs 2022-03-30T21:07:20.144Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/scmutil.py", line 153, in callcatch
[vcs 2022-03-30T21:07:20.144Z]     return func()
[vcs 2022-03-30T21:07:20.144Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 460, in _runcatchfunc
[vcs 2022-03-30T21:07:20.144Z]     return _dispatch(req)
[vcs 2022-03-30T21:07:20.144Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 1274, in _dispatch
[vcs 2022-03-30T21:07:20.145Z]     lui, repo, cmd, fullargs, ui, options, d, cmdpats, cmdoptions
[vcs 2022-03-30T21:07:20.145Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 918, in runcommand
[vcs 2022-03-30T21:07:20.145Z]     ret = _runcommand(ui, options, cmd, d)
[vcs 2022-03-30T21:07:20.145Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 1285, in _runcommand
[vcs 2022-03-30T21:07:20.146Z]     return cmdfunc()
[vcs 2022-03-30T21:07:20.146Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 1271, in <lambda>
[vcs 2022-03-30T21:07:20.146Z]     d = lambda: util.checksignature(func)(ui, *args, **strcmdopt)
[vcs 2022-03-30T21:07:20.146Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/util.py", line 1887, in check
[vcs 2022-03-30T21:07:20.147Z]     return func(*args, **kwargs)
[vcs 2022-03-30T21:07:20.147Z]   File "/usr/local/src/robustcheckout.py", line 211, in robustcheckout
[vcs 2022-03-30T21:07:20.147Z]     noupdate=noupdate,
[vcs 2022-03-30T21:07:20.147Z]   File "/usr/local/src/robustcheckout.py", line 786, in _docheckout
[vcs 2022-03-30T21:07:20.147Z]     timeit("sparse_update_config", "sparse-update-config"),
[vcs 2022-03-30T21:07:20.147Z] AttributeError: __enter__
```

**Comment by aerickson** [comment]
building as `20220331T130939`

build successful: `03-31 11:44:49.190 20220331T130939: digest: sha256:3326add76cf762a06c80d51daadf589878b2fd33d7eb132f3418a1711f20f83f size: 5967`

test result: failure
```
[vcs 2022-03-31T19:02:11.281Z] adding file changes
[vcs 2022-03-31T19:02:11.779Z] added 4 changesets with 5 changes to 4 files (+1 heads)
[vcs 2022-03-31T19:02:11.780Z] new changesets 66b5f8936fa8:59ec5e25b59b (4 drafts)
[vcs 2022-03-31T19:02:12.087Z] (setting sparse config to profile build/sparse-profiles/perftest)
[vcs 2022-03-31T19:02:12.089Z] ** unknown exception encountered, please report by visiting
[vcs 2022-03-31T19:02:12.089Z] ** https://mercurial-scm.org/wiki/BugTracker
[vcs 2022-03-31T19:02:12.089Z] ** Python 3.6.9 (default, Dec  8 2021, 21:08:43) [GCC 8.4.0]
[vcs 2022-03-31T19:02:12.089Z] ** Mercurial Distributed SCM (version 5.9.3)
[vcs 2022-03-31T19:02:12.089Z] ** Extensions loaded: histedit, purge, rebase, robustcheckout, share, sparse
[vcs 2022-03-31T19:02:12.089Z] Traceback (most recent call last):
[vcs 2022-03-31T19:02:12.089Z]   File "/usr/local/bin/hg", line 61, in <module>
[vcs 2022-03-31T19:02:12.089Z]     dispatch.run()
[vcs 2022-03-31T19:02:12.089Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 144, in run
[vcs 2022-03-31T19:02:12.089Z]     status = dispatch(req)
[vcs 2022-03-31T19:02:12.089Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 250, in dispatch
[vcs 2022-03-31T19:02:12.089Z]     status = _rundispatch(req)
[vcs 2022-03-31T19:02:12.089Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 294, in _rundispatch
[vcs 2022-03-31T19:02:12.089Z]     ret = _runcatch(req) or 0
[vcs 2022-03-31T19:02:12.089Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 470, in _runcatch
[vcs 2022-03-31T19:02:12.089Z]     return _callcatch(ui, _runcatchfunc)
[vcs 2022-03-31T19:02:12.089Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 480, in _callcatch
[vcs 2022-03-31T19:02:12.089Z]     return scmutil.callcatch(ui, func)
[vcs 2022-03-31T19:02:12.090Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/scmutil.py", line 153, in callcatch
[vcs 2022-03-31T19:02:12.090Z]     return func()
[vcs 2022-03-31T19:02:12.090Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 460, in _runcatchfunc
[vcs 2022-03-31T19:02:12.090Z]     return _dispatch(req)
[vcs 2022-03-31T19:02:12.090Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 1274, in _dispatch
[vcs 2022-03-31T19:02:12.090Z]     lui, repo, cmd, fullargs, ui, options, d, cmdpats, cmdoptions
[vcs 2022-03-31T19:02:12.090Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 918, in runcommand
[vcs 2022-03-31T19:02:12.090Z]     ret = _runcommand(ui, options, cmd, d)
[vcs 2022-03-31T19:02:12.090Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 1285, in _runcommand
[vcs 2022-03-31T19:02:12.090Z]     return cmdfunc()
[vcs 2022-03-31T19:02:12.090Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/dispatch.py", line 1271, in <lambda>
[vcs 2022-03-31T19:02:12.090Z]     d = lambda: util.checksignature(func)(ui, *args, **strcmdopt)
[vcs 2022-03-31T19:02:12.091Z]   File "/usr/local/lib/python3.6/dist-packages/mercurial/util.py", line 1886, in check
[vcs 2022-03-31T19:02:12.091Z]     return func(*args, **kwargs)
[vcs 2022-03-31T19:02:12.091Z]   File "/usr/local/src/robustcheckout.py", line 211, in robustcheckout
[vcs 2022-03-31T19:02:12.091Z]     noupdate=noupdate,
[vcs 2022-03-31T19:02:12.091Z]   File "/usr/local/src/robustcheckout.py", line 786, in _docheckout
[vcs 2022-03-31T19:02:12.091Z]     timeit("sparse_update_config", "sparse-update-config"),
[vcs 2022-03-31T19:02:12.091Z] AttributeError: __enter__
```

**Comment by aerickson** [comment]
building as `20220331T141348`

build successful: `03-31 12:27:22.486 20220331T141348: digest: sha256:49e46166f0f9a2b40199b505a51fb476d327277701391b0417d99cd1d7be7f78 size: 5967`

test results
  - `view-fenix` job with hg clone: success
  - more tests (https://treeherder.mozilla.org/jobs?repo=try&revision=5e069fd5af3482cbf305fb94a5c39fdd2affc6a6): pending

**Review by davehouse — APPROVED** [review]
:+1: great! And thx this reminds me to check where we're at on the other hw workers

**Pull request merged**
