### PR TITLE
support Samsug A51 (A515F)

### PR DESCRIPTION
**Pull request by aerickson**
Add support for detection and control of charging for the Samsung A51 (A515F) device.

### CODE REVIEW

**Comment by aerickson** [comment]
ba84701: built as `11-22 13:53:59.244 20211122T154221: digest: sha256:428fe118e673fbb9324ded6b19c821298b1d385958b554f1cc38b2c38492f143 size: 5967`

**Comment by aerickson** [comment]
7118905: `20211130T120953`

```
11-30 10:20:45.165 20211130T120953: digest: sha256:a1b0fa3f3a46dae7d595ca0cb1ee9a8c6ab66dc4972a51d7d5b41c9cbbb15af0 size: 5967
```

**Comment by aerickson** [comment]
Doesn't explode any longer on A51s, but we need to do extended testing.

**Comment by aerickson** [comment]
Extended testing done. The image is now set as default (via https://github.com/mozilla-platform-ops/mozilla-bitbar-devicepool/pull/13).

**Review by davehouse — APPROVED** [review]

**Pull request merged**
